/**
 * Provider adapter contracts (RapidAPI/Zillow request and response shapes).
 *
 * Canonical, provider-agnostic DTOs belong in `@/contracts/domain`.
 *
 * @see Naming and import rules in `src/contracts/index.ts`
 */

export {
  providerErrorCategories,
  providerErrorCategorySchema,
  providerErrorDebugSchema,
  providerErrorSchema,
  providerRateLimitHeadersSchema,
  providerStepErrorSchema,
  providerUserMessages,
  isProviderError,
  isProviderStepError,
  type ProviderError,
  type ProviderErrorCategory,
  type ProviderStepError,
} from "@/contracts/providers/errors";
export {
  providerNameSchema,
  providerSourceMetadataSchema,
  type ProviderName,
  type ProviderSourceMetadata,
} from "@/contracts/domain";
export {
  comparablesEndpointPath,
  comparablesItemSchema,
  comparablesPropertyPayloadSchema,
  comparablesProviderIdSchema,
  comparablesRequestSchema,
  comparablesResponseSchema,
  comparablesResultItemSchema,
  comparablesToolKey,
  comparablesV1CompStatus,
  formatListingSearchListPriceRange,
  formatListingSearchLocation,
  LISTING_SEARCH_MAX_PAGE,
  LISTING_SEARCH_V1_MAX_RESULTS,
  listingSearchEndpointPath,
  listingSearchListingItemSchema,
  listingSearchPropertySchema,
  listingSearchRequestSchema,
  listingSearchResponseSchema,
  listingSearchToolKey,
  listingSearchV1ListingStatus,
  propertyDetailEndpointPath,
  propertyDetailItemSchema,
  propertyDetailsPayloadSchema,
  propertyDetailRequestSchema,
  propertyDetailResponseSchema,
  propertyDetailToolKey,
  propertyLookupRequestSchema,
  propertyLookupResponseSchema,
  propertyLookupToolKey,
  rentEstimateEndpointPath,
  rentEstimatePayloadSchema,
  rentEstimateProviderIdSchema,
  rentEstimateRequestSchema,
  rentEstimateResponseSchema,
  rentEstimateToolKey,
  rentEstimateV1MissingBehavior,
  ZILLOW_PROVIDER_NAME,
  zillowAddressFragmentSchema,
  zillowMoneyFragmentSchema,
  zillowProviderIdSchema,
  type ComparablesItem,
  type ComparablesPropertyPayload,
  type ComparablesProviderId,
  type ComparablesRequest,
  type ComparablesResponse,
  type ComparablesResultItem,
  type ListingSearchListingItem,
  type ListingSearchProperty,
  type ListingSearchRequest,
  type ListingSearchResponse,
  type PropertyDetailItem,
  type PropertyDetailsPayload,
  type PropertyDetailRequest,
  type PropertyDetailResponse,
  type PropertyLookupRequest,
  type PropertyLookupResponse,
  type RentEstimatePayload,
  type RentEstimateProviderId,
  type RentEstimateRequest,
  type RentEstimateResponse,
  type ZillowAddressFragment,
  type ZillowMoneyFragment,
  type ZillowProviderId,
} from "@/contracts/providers/zillow";
