/**
 * @deprecated Import from `@/contracts/domain/analysis` instead.
 */

export {
  areaAggregateSchema,
  areaGroupingLevelSchema,
  metricBundleSchema,
  metricReasonCodeSchema,
  metricValueAvailableSchema,
  metricValueMissingSchema,
  metricValueNotApplicableSchema,
  metricValueSchema,
  propertyScoreAvailableSchema,
  propertyScoreSchema,
  propertyScoreUnavailableSchema,
  scoreComponentSchema,
  scoreReasonCodeSchema,
  scoreReasonSchema,
  scoreReasonSeveritySchema,
  summarySectionSchema,
  topPropertySummarySchema,
  workflowSummarySchema,
  type AreaAggregate,
  type AreaGroupingLevel,
  type MetricBundle,
  type MetricReasonCode,
  type MetricValue,
  type PropertyScore,
  type ScoreComponent,
  type ScoreReason,
  type ScoreReasonCode,
  type ScoreReasonSeverity,
  type SummarySection,
  type TopPropertySummary,
  type WorkflowSummary,
} from "@/contracts/domain/analysis";
